#server:
#  port: 8081
#
#spring:
#  application:
#    name: product-service
#
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test-product?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&useSSL=true
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848