server:
  port: 8051

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-user?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #解决The bean 'xxx', defined in class path resource [com/liangzhicheng/config/shiro/ShiroConfig.class],
  #could not be registered. A bean with that name has already been defined in file
  #[D:\WorkDirectory\IdeaProjects\microservice-basic-framework\user-server\target\classes\com\liangzhicheng\config\shiro\PermRealm.class]
  #and overriding is disabled.
  main:
    allow-bean-definition-overriding: true

area-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载均衡策略