server:
  port: 8041

spring:
  application:
    name: consumer-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    stream:
      binders: #需要绑定rabbitmq的服务信息
        defaultRabbit: #定义的名称,用于binding整合
          type: rabbit #消息组件类型
          environment: #环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

      bindings: #服务的整合处理
        input: # 名字是一个通道的名称
          destination: rabbitExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型,本次为json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: consumer #添加分组属性,可用于多服务，服务以轮询的方式接收消息,实现多服务重复消费问题

management:
  endpoints:
    web:
      exposure:
        include: "*"