server:
  port: 8031

spring:
  application:
    name: provider-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-order?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    stream:
      binders: #需要绑定rabbitmq的服务信息
        defaultRabbit: #定义的名称,用于binding整合
          type: rabbit #消息组件类型
          environment: #环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

      bindings: #服务的整合处理
        output: # 名字是一个通道的名称
          destination: rabbitExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型,本次为json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

management:
  endpoints:
    web:
      exposure:
        include: "*"